name: 'Setup CSP'
description: 'Set up your GitHub Actions workflow with a specific version of csp'
branding:
  icon: 'play'
  color: 'green'
inputs:
  version:
    description: 'The version to use'
    default: latest
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
